### PR TITLE
Environment variables and comment key DNS finding

### PR DESCRIPTION
**Pull request by almulalic**
Hi Alex thanks for the initial repo, it really helped me alot.

This is currently the most straightforward solution for resolving this problem but sadly it resolved on manually entering which domains should be updated which is fine, in case of few domains, but in my case I am working with 10+ static records and I constantly experiment with services. To resolve this issue I added a function that will (levaraging the cloudflare API) get all DNS records which contain a COMMENT_KEY (In my case DYN-IP). This way, I only need to define it once while creating the DNS record (programatically or manually) and it would be picked up next time it refreshes. This is still a WIP as I'm testing it but I would love to get your feedback on this.

Also, due to the fact that I'm a bit (over)aware of security and exposing my credentials I rewrote parts of the app that referenced sensitive data like api keys and emails to be loaded from dotenv.

WIP

### CODE REVIEW

**Comment by paulhayes** [comment]
This is a really important fix, thanks for suggesting it. @alexplesoiu could you please merge this pull request?

**Comment by alexplesoiu** [comment]
Hello @almulalic , thank you for your interest in this project. Until now I thought that no one has interest in this project so I stopped the development for it. I also had in mind some new features for it including support for configuration files. 

Please also update the README file and add support for record_type, content, ttl, proxied fields for Cloudflare.
I will also update the medium tutorial for the project when you finish.

Thank you for the ping, @paulhayes ! I was away for ~3 weeks.

**Comment by SpasovskiFilip** [comment]
Really great idea. I also have around 15 subdomains and playing around with services, but I just added all of those in the main.py file. But I did do a few changes that I thought might improve it.

In the [PR I created](https://github.com/alexplesoiu/dns-updater/pull/1) I replaced the API key and Email with an API Token, because I think it's safer to control the API Token and what access it has, instead of the API key for the whole CF account.
Also the request only needs the `'Authorization': 'Bearer ' + API_TOKEN,` instead of adding an Email and API Key.

Another note I have is that when running this with docker, I added a volume mapping to the main.py file, so i don't have to rebuild the container every time there's a change to the faile.

**Comment by almulalic** [comment]
That sounds great. Let me merge your changes with mine and we can continue it from that point

**Comment by alexplesoiu** [comment]
For a while, until everything is ready, we will continue the development on the dev branch until a full release is ready.

If we start the development of this tool, we should also provide a better support for docker (like setup via env vars / config files), overall good security and easy setup. Being a cf based tool, we should support other domain configuration on cloudflare, like proxy, ttl, ssl, etc. We also need good documentation.

What do you think @SpasovskiFilip @almulalic @paulhayes ?

I have to think about how we organize the development for the next versions. Maybe I will make a project and a roadmap + a communication channel. I think we can use discussions for this.

**Comment by SpasovskiFilip** [comment]
I think it's a great idea, especially because the extensibility of this tool is much bigger than I thought.
I'll start a discussion with the few ideas I have on this and we can expand on those.

**Comment by almulalic** [comment]
Github issues + releases + ghcr.io docker images would be a good start. Testing would be even better if something can be used for testing against cloudflare. Communication channel can be whatever you like, for now maybe the github issues could be enough. @SpasovskiFilip can you reopen your PR against dev so we have the changes on dev?
Also @alexplesoiu push permissions would help to avoid fork PR's

**Comment by alexplesoiu** [comment]
For now, push permissions won't be allowed. I need to see each PR before the merge so I know what's going on. Maybe some PRs will be rejected for some reasons. We will use GitHub discussions for communication.

**Pull request merged**
